### ISSUE TITLE
is possible to change navigation drawer toggle icon from left-to-right side?

### ISSUE THREAD

**Issue by tormahiri** [PaulTR/AndroidDemoProjects#6]
hi paul
i want to change navigation toggle drawer icon from left to right side ,is possible ?

**Comment by PaulTR** [comment]
Dunno, someone has probably asked that on stackoverflow.com. Check there.

**Comment by tormahiri** [comment]
i have been checked many time but there are not solution for navigation drawer toggle ,have you any idea ? i think that is not possible now beacuse android platform default will not support right-to left of navigation drawer toggle icon

**Comment by PaulTR** [comment]
Like I said, I don't know. Closing as this is a comment, and not an actual issue.
