### ISSUE TITLE
How do you import any of this projects to Android studio

### ISSUE THREAD

**Issue by julian-ramos** [PaulTR/AndroidDemoProjects#7]
Hi Paul,

Great material, thanks for sharing. I have tried to import some of the demos to Android studio but I haven't been successful so far. Here is the message that I get:

Error:(16, 0) Gradle DSL method not found: 'runProguard()'
Possible causes:<ul><li>The project 'WearMessageApi' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

Any idea how to solve this issue?

Best,

**Comment by PaulTR** [comment]
Offhand I don't know. Try updating the gradle files to use the most recent version of gradle and the wrapper. Or you can just take the Java and xml files and copy them into your own project.
