### ISSUE TITLE
Broadcast video not working

### ISSUE THREAD

**Issue by pol2095** [PaulTR/AndroidDemoProjects#8]
Hello,

I try pour simple, I can connect to my chromecast, but the video is not broadcasted when I click on the button "play video" (the button stay on play vidéo, isSuccess() is not dispatcher)

Thanks

**Comment by PaulTR** [comment]
Have you set up your own Chromecast developer account and receiver?

**Comment by pol2095** [comment]
on cast.google.com/publish/#/overview, I add the chomecast serial number -> "Ready For Testing",
And I add a "Remote Display Receiver" -> I use the "Application ID" on my android app
