### ISSUE TITLE
How to play songs in android auto dashboard

### ISSUE THREAD

**Issue by vanseinfo** [PaulTR/AndroidDemoProjects#9]
In this  app songs playing in phone only. i want our songs  are play  android auto like mediabrowserservice how to do? plz suggest me....

**Comment by PaulTR** [comment]
You need to be hooked up to an Auto device to browse media and play on the device.

**Comment by vanseinfo** [comment]
I'm testing with DHU simulator. Mobile hooked up with cpu. And Browsable media works works but songs play only mobile not in DHU how to fix?

**Comment by vanseinfo** [comment]
No progress update in DHU how to do?
